import java.nio.file.Paths

plugins {
  id 'fabric-loom' version '0.12-SNAPSHOT'
  // id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

// base {
//	archivesName = project.archives_base_name
//}
archivesBaseName = project.archives_base_name

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

loom {
  // comment below line when using older MC versions (e.g. 1.16.1)
	// splitEnvironmentSourceSets()

  runs {
    client {
      // runDir file("/Users/nathaniel/Library/Application Support/ModrinthApp/profiles/SpeedrunPack (1)")
      runDir Paths.get(System.getProperty("user.home"), "Library/Application Support/ModrinthApp/profiles/SpeedrunPack (1)").toString()
    }
    server {
      runDir "run/server"
    }
  }

	mods {
		"modid" {
			sourceSet sourceSets.main
			// sourceSet sourceSets.client
		}
	}

}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	// mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
  mappings "net.fabricmc:yarn:1.16.1+build.21:v2"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

  fileTree(dir: "/Users/nathaniel/Library/Application Support/ModrinthApp/profiles/SpeedrunPack (1)/mods", include: "*.jar").each { modFile ->
    modRuntimeOnly(files(modFile))
  }

  // WebSocket library
  implementation "org.java-websocket:Java-WebSocket:1.5.3"
  include "org.java-websocket:Java-WebSocket:1.5.3"

  // MixinExtras is required by many 1.16.1 speedrun mods (StandardSettings, etc.)
  implementation "io.github.llamalad7:mixinextras-fabric:0.3.5"
  include "io.github.llamalad7:mixinextras-fabric:0.3.5"

  // Annotation processor for MixinExtras
  annotationProcessor "io.github.llamalad7:mixinextras-fabric:0.3.5"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 8
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
	inputs.property "archivesName", project.archives_base_name

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
